// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDCFdKeY4wFJllKIo7tjPKxtHU8ZDp1aE',
    appId: '1:1018896965719:web:6db0ba32b064f07b86c312',
    messagingSenderId: '1018896965719',
    projectId: 'talearnt-app',
    authDomain: 'talearnt-app.firebaseapp.com',
    storageBucket: 'talearnt-app.firebasestorage.app',
    measurementId: 'G-1H8JVWWGL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLntE59PfhaPW8eHqsTHR5FB0nJz106Ek',
    appId: '1:1018896965719:android:b7441785902756ed86c312',
    messagingSenderId: '1018896965719',
    projectId: 'talearnt-app',
    storageBucket: 'talearnt-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2godsC6LzSfj7sO4tn3cgzSZMToIz38c',
    appId: '1:1018896965719:ios:676bf2e852f562d386c312',
    messagingSenderId: '1018896965719',
    projectId: 'talearnt-app',
    storageBucket: 'talearnt-app.firebasestorage.app',
    iosBundleId: 'com.example.appFrontTalearnt',
  );
}
